# Generated by Django 2.1.5 on 2019-02-07 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190207_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 7, 16, 43, 654040, tzinfo=utc)),
        ),
    ]
