# Generated by Django 2.1.5 on 2019-02-07 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190207_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 11, 26, 5, 984824, tzinfo=utc)),
        ),
    ]
