# Generated by Django 2.1.5 on 2019-02-07 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190207_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 7, 12, 14, 44, 408518, tzinfo=utc)),
        ),
    ]
