# Generated by Django 2.1.5 on 2019-02-08 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20190208_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 8, 10, 19, 22, 911955, tzinfo=utc)),
        ),
    ]
